### ISSUE TITLE
Add icon's color

### ISSUE THREAD

**Issue by poonwu** [jaketrent/react-social-icons#18]
The current version only support changing color of the mask. However, it doesn't support replacing the actual logo with arbitrary color.

**Comment by haysclark** [comment]
I have a workaround, at least for Chrome.  In your code set the color of the icon to ```currentColor```. This seems to trickle down to the SVG's ```fill``` value, then you can mess with the ```color``` and ```background``` via CSS.  I got the idea from this [cascading-svg-fill-color article](https://css-tricks.com/cascading-svg-fill-color/)

**Example JSX**
```jsx
<SocialIcon className="my-social-icon" url={url} color="currentColor" />
```

**Example CSS**
```css
.my-social-icon .social-svg {
    color: #BBC7CC;
}

.my-social-icon .social-svg:hover {
    color: #55acee;
    background: white;
}
```
